# Generated by Django 3.2.20 on 2023-08-11 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmodel',
            name='task_title',
            field=models.CharField(default='task', max_length=30),
        ),
    ]
